<a href="https://colab.research.google.com/github/LauraJDiaz/Ciencia-De-Datos/blob/main/Ciencia_de_Datos_Dataframe_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Dataframes
1. Columnas (Features - caracteristicas)
2. Filas (Registros)

Siempre se deben importar las librerias de Numpy y pandas

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Convertir de listas a dataframe
Ventas=pd.Series([22,15,71])
Ventas

0    22
1    15
2    71
dtype: int64

In [ ]:
ventas=pd.Series([22,15,71],index=['Enero','Febrero','Marzo'])
ventas

Enero      22
Febrero    15
Marzo      71
dtype: int64

In [ ]:
ventas["Enero"]

22

In [ ]:
ventas.dtype

dtype('int64')

In [ ]:
#Para visualizar features
ventas.index


Index(['Enero', 'Febrero', 'Marzo'], dtype='object')

In [ ]:
#Para obtener los valores de la feature
ventas.values

array([22, 15, 71])

In [ ]:
ventas.name="Ventas del 2025"
ventas

Enero      22
Febrero    15
Marzo      71
Name: Ventas del 2025, dtype: int64

In [ ]:
#Para nombrar el index
ventas.index.name="Meses"
ventas

Meses
Enero      22
Febrero    15
Marzo      71
Name: Ventas del 2025, dtype: int64

In [ ]:
ventas.shape

(3,)

1. Los diccionarios tienen una clave unica, y un valor asociado a la clave (string)
2. No se pueden indezar (No se sabe la pocision de datos)
3. Son mutables

In [ ]:
diccionario={"Enero":22,"Febrero":15,"Marzo":71}
type(diccionario)

dict

In [ ]:
#Convertir diccionario a dataframe
ventas1=pd.Series(diccionario)
ventas1

Enero      22
Febrero    15
Marzo      71
dtype: int64

In [ ]:
alex=pd.Series(diccionario,index=["Enero","Febrero","Marzo","Abril"])
alex

Enero      22.0
Febrero    15.0
Marzo      71.0
Abril       NaN
dtype: float64

In [ ]:
medidas=pd.DataFrame(
    {"Humedad":[41,20,30,80],
     "Salinidad":[22,15,30,80],
     "Sensórica":["Sí","No","No","No"],
     "Acidez":["alta","media","baja","baja"],
     "ph":[1,7,14,13]},
    index=["La Ureña","Paso Chino","La Laguna","Los Teres"],
)

medidas

Humedad  Salinidad Sensórica Acidez  ph
La Ureña         41         22        Sí   alta   1
Paso Chino       20         15        No  media   7
La Laguna        30         30        No   baja  14
Los Teres        80         80        No   baja  13

In [ ]:
medidas.index.name="Meses"
medidas

Humedad  Salinidad Sensórica Acidez  ph
Meses                                              
La Ureña         41         22        Sí   alta   1
Paso Chino       20         15        No  media   7
La Laguna        30         30        No   baja  14
Los Teres        80         80        No   baja  13

In [ ]:
medidas[["ph","Humedad"]]


ph  Humedad
Meses                  
La Ureña     1       41
Paso Chino   7       20
La Laguna   14       30
Los Teres   13       80

In [ ]:
#Nombres Filas y columnas
medidas.axes

[Index(['La Ureña', 'Paso Chino', 'La Laguna', 'Los Teres'], dtype='object', name='Meses'),
 Index(['Humedad', 'Salinidad', 'Sensórica', 'Acidez', 'ph'], dtype='object')]

In [ ]:
medidas.shape

(4, 5)

###Ejercicios
Dados los siguientes diccionarios, convertirlos en datagramas y usar todos los métodos aprendidos:

```
elementos={"número atómico":[1,6,47,88],
"Masa atómica":[1,12,107,226],
"Familia":["No metal","No metal","Metal","Metal"]}
```
Agregar como registros el nombre de los elementos

2. Convertir en dataframe el siguiente conjunto de medidas
```
medida_2020={"Ag":2,"Au":5,"Cu":3,"Pt:2}
medida_2021={"Ag":4,"Au":3,"Cu":6,"Pt:1}
medida_2022={"Ag":8,"Au":2,"Cu":15,"Pt:0}
medida_2023={"Ag":5,"Au":1,"Cu":0,"Pt:5}
medida_2024={"Ag":7,"Au":0,"Cu":3,"Pt:2}
medida_20205={"Ag":9,"Au":1,"Cu":3,"Pt:5}
```
Tenga en cuenta que los registros son los meses de medida y las features deben ser los elementos

In [ ]:
elementos=pd.DataFrame(
    {"Número atómico":[1,6,47,88],
    "Masa atómica":[1,12,107,226],
    "Familia":["No metal","No metal","Metal","Metal"]},
    index=["Hidrogeno","Carbono","Plata","Radio"])

elementos



Número atómico  Masa atómica   Familia
Hidrogeno               1             1  No metal
Carbono                 6            12  No metal
Plata                  47           107     Metal
Radio                  88           226     Metal

In [ ]:
elementos.index.name="Elementos"
elementos

Número atómico  Masa atómica   Familia
Elementos                                        
Hidrogeno               1             1  No metal
Carbono                 6            12  No metal
Plata                  47           107     Metal
Radio                  88           226     Metal

In [ ]:
elementos.index


Index(['Hidrogeno', 'Carbono', 'Plata', 'Radio'], dtype='object', name='Elementos')

In [ ]:
elementos.dtypes

Número atómico     int64
Masa atómica       int64
Familia           object
dtype: object

In [ ]:
elementos.axes

[Index(['Hidrogeno', 'Carbono', 'Plata', 'Radio'], dtype='object', name='Elementos'),
 Index(['Número atómico', 'Masa atómica', 'Familia'], dtype='object')]

In [ ]:
elementos.values

array([[1, 1, 'No metal'],
       [6, 12, 'No metal'],
       [47, 107, 'Metal'],
       [88, 226, 'Metal']], dtype=object)

In [ ]:
elementos[["Familia","Número atómico"]]

Familia  Número atómico
Elementos                          
Hidrogeno  No metal               1
Carbono    No metal               6
Plata         Metal              47
Radio         Metal              88

In [ ]:
elementos.shape

(4, 3)

In [ ]:
medidas=pd.DataFrame(
    {"2020":{"Ag":2,"Au":5,"Cu":3,"Pt":2},
    "2021":{"Ag":4,"Au":3,"Cu":6,"Pt":1},
    "2022":{"Ag":8,"Au":2,"Cu":15,"Pt":0},
    "2023":{"Ag":5,"Au":1,"Cu":0,"Pt":5},
    "2024":{"Ag":7,"Au":0,"Cu":3,"Pt":2},
    "2025":{"Ag":9,"Au":1,"Cu":3,"Pt":5}})
medidas

2020  2021  2022  2023  2024  2025
Ag     2     4     8     5     7     9
Au     5     3     2     1     0     1
Cu     3     6    15     0     3     3
Pt     2     1     0     5     2     5

In [ ]:
medidas.index.name="Elementos"
medidas

2020  2021  2022  2023  2024  2025
Elementos                                    
Ag            2     4     8     5     7     9
Au            5     3     2     1     0     1
Cu            3     6    15     0     3     3
Pt            2     1     0     5     2     5

In [ ]:
medidas.dtypes

2020    int64
2021    int64
2022    int64
2023    int64
2024    int64
2025    int64
dtype: object

In [ ]:
medidas.axes

[Index(['Ag', 'Au', 'Cu', 'Pt'], dtype='object', name='Elementos'),
 Index(['2020', '2021', '2022', '2023', '2024', '2025'], dtype='object')]

In [ ]:
medidas.values

array([[ 2,  4,  8,  5,  7,  9],
       [ 5,  3,  2,  1,  0,  1],
       [ 3,  6, 15,  0,  3,  3],
       [ 2,  1,  0,  5,  2,  5]])

In [ ]:
medidas.shape

(4, 6)

In [ ]:
medidas[["2023","2021"]]

2023  2021
Elementos            
Ag            5     4
Au            1     3
Cu            0     6
Pt            5     1